import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['greek'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  const backgroundImageStyle = {
    backgroundImage: `url(${"https://c4.wallpaperflare.com/wallpaper/1/323/656/league-of-legends-noxus-hd-wallpaper-preview.jpg"})`
   
  };

  return (
    <html lang="en">
      <body className={`${inter.className} ` } >{children}</body>
    </html>
  )
}
